FROM node:18-alpine AS builder
ENV NODE_ENV production
# Add a work directory
WORKDIR /usr/src/app
# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm install --omit=dev
# Copy app files
COPY . .
# Build the app
RUN npm run build

# Bundle static assets with nginx
FROM node:18-alpine as production
ENV NODE_ENV production
# Copy built assets from builder
COPY --from=builder /usr/src/app/build /usr/src/app
